# スプラッシュ画像に使いたい画像が格納されているフォルダの絶対パス
# バックスラッシュは \\ にするか、または / に変更
# デフォルト: 空欄
src_dir = "C:/Users/Assault/Pictures/VRChat/EACSS"
# 画像のリサイズ先解像度
# VRChat以外でも使うとき、EACのスプラッシュ画像が800x450でない場合、ここを変更
# デフォルト: 800x450
res_width  = 800
res_height = 450